apiVersion: v1
kind: Pod
metadata:
  name: secondPod
  labels:
    podType: testPod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 1500m
        memory: 1.5Gi
    command:
    - "/bin/sh"
    - "-c"
    - "--"
    args:
    - "myScript.sh"