apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filemanager
  namespace: dev-dev
spec:
  template:
    spec:
      containers:
        - image: image-ci:latest
          env:
            - name: nmspc
              value: dev-dev
            - name: SERVICENAME
              value: filemanager
          ports:
            - containerPort: 5000

#this knative service did not work with tag in the image URI. it had to be replaced with digest/hash
# WHAT DID NOT WORK: 
  # image-ci:latest
    # Unable to fetch image "image-ci:latest": failed to resolve image to digest: Get "amazonaws.com/v2/": context deadline exceeded
# WHAT WORKED:
  # amazonaws.com/image-ci@sha256:dfe0d2d4e91d7f0b1b2de7599